<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ext_update_info"
 *
 * Auto generated by Extension Builder 2019-10-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Extension Update Info',
    'description' => 'Informs about existing updates of extensions',
    'category' => 'plugin',
    'author' => 'Sven Jürgens',
    'author_email' => '',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
